### ISSUE TITLE
Allow inject SQLManager

### ISSUE THREAD

**Issue by shaokuuipo** [actframework/act-beetlsql#13]
We need `org.beetl.sql.core.SQLManager` to register customised ID generator, it would good to make it able to inject `org.beetl.sql.core.SQLManager` instance on app start

**Comment by greenlaw110** [comment]
@shaokuuipo try act-beetlsql-1.7.0-SNAPSHOT

Usage:

```java
class Demo {
    @Inject // in case default db configuration is BeetlSqlPlugin
    private SQLManager defSqlMgr;
    
    @Inject
    @Named("foo") // in case "foo" db configuration is BeetlSqlPlugin
    private SQLManager fooMgr;
}
```

**Comment by shaokuuipo** [comment]
It works for me, Thank you!
