### ISSUE TITLE
Failed to insert data

### ISSUE THREAD

**Issue by zoze0** [actframework/act-beetlsql#9]
**javabean:**

```java
public class Act {

	private int testA;
	private int testB;

	public int getTestA() {
		return testA;
	}

	public void setTestA(int testA) {
		this.testA = testA;
	}

	public int getTestB() {
		return testB;
	}

	public void setTestB(int testB) {
		this.testB = testB;
	}
```

**controller:**

```java
@GetAction("/act")
	@JsonView
	public Act act() {
		Act act = new Act();
		act.setTestA(100);
		act.setTestB(200);

		System.out.println(act);
		
		actDao.insert(act);
		return act;
	}
```

**dao:**

```java
public interface ActDao extends BaseMapper<Act> {

}
```

执行的时候,
![i1](https://user-images.githubusercontent.com/20562449/45585441-d7752d80-b916-11e8-9275-c4edc7c455d5.png)

我用了springboot测试了一下,代码都是复制过去的,act换成springboot,act-beetlsql换成beetl-framework-starter是没问题的
![i2](https://user-images.githubusercontent.com/20562449/45585450-fd9acd80-b916-11e8-97dd-399c63f345dd.png)

**Comment by zoze0** [comment]
degub一下发现不同的地方在 SQLmanager里面,springboot进入了if,而act没进入
![diff](https://user-images.githubusercontent.com/20562449/45585543-b0b7f680-b918-11e8-9378-9d20fe5d1e77.png)


springboot:
![ok](https://user-images.githubusercontent.com/20562449/45585549-d513d300-b918-11e8-8240-eaff4f364ef0.png)
act:
![err](https://user-images.githubusercontent.com/20562449/45585554-dba24a80-b918-11e8-80ef-eb94c8371ec9.png)

**Comment by greenlaw110** [comment]
@licardoY Act 类的上面加上这个:

```java
@With(BeetlSqlTransactional.class)
```

**Comment by zoze0** [comment]
我加上了,但是并没有变化,insert时候还是空的

**Comment by zoze0** [comment]
参考了`act-demo-apps/todo-beetlsql` 项目,经过对比将demo里的`TodoItem`
```java
 private Long id;
 private String desc;
```
改为
```java
private int testA;
private String testB;
```
insert也出现了空
```java
insert into `todoitem` () VALUES ()
```

**Comment by greenlaw110** [comment]
@licardoY 

1. Please add `@Entity` annotation to your model class `Act` (BTW, it is not a good idea to use name `Act` here).
2. Please add `@Id` to your ID field
3. If you need system to generate ID automatically, please add `@AutoId` to your getter method of ID field.

**Comment by zoze0** [comment]
> 主键需要通过注解来说明，如@AutoID，或者@AssignID等，但如果是自增主键，且属性是名字是id，则不需要注解，自动认为是自增主键

http://ibeetl.com/guide/#beetlsql
